name: Deploy to GitHub Pages

on:
  push:
    branches:
      - pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload `src/` folder to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
